[package]
name = "json_key_extractor"
version = "0.1.0"
authors = ["Davide Giovannini <giovannini.davide90@gmail.com>"]

[dependencies]
serde_json = "1.0"
lazy_static = "1.0"
regex = "1.0"

crossbeam = "0.4"
num_cpus = "1.0"

structopt = "0.2.8"
structopt-derive = "0.2.8"

ansi_term = "0.11"
prettytable-rs="0.8.0"
atty = "0.2.11"

[dev-dependencies]
quickcheck = "0.7"
