[package]
name = "json_key_extractor"
version = "0.1.1"
authors = ["Davide Giovannini <giovannini.davide90@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
lazy_static = "1"
regex = "1"

crossbeam = "0.7"
num_cpus = "1.9"

structopt = "0.2"

ansi_term = "0.11"
prettytable-rs="0.8"
atty = "0.2"

[dev-dependencies]
quickcheck = "0.8"
rand = "0.6"
