[package]
name = "json_key_extractor"
version = "0.1.0"
authors = ["Davide Giovannini <giovannini.davide90@gmail.com>"]

[dependencies]
serde_json = "1.0"
argparse = "*"
lazy_static = "0.2.8"
regex = "0.2"

[dev-dependencies]
quickcheck = "0.3"
